### ISSUE TITLE
don't inject istio by default

### ISSUE THREAD

**Issue by rootfs** [knative/eventing-sources#100]
istio sidecar is injected into container source by default [here](https://github.com/knative/eventing-sources/blob/master/pkg/controller/containersource/resources/deployment.go#L60). And there is no document on it or service entry. I notice only container source and gcp pubsub have it, github source doesn't have it (a right thing imo)

I may have missed the big picture, but is there a reason to force istio on? @grantr @n3wscott

**Comment by grantr** [comment]
The Istio sidecar is needed to communicate with the in-memory channel which uses Istio. For now Istio is required for channel implementations, but that may not always be true (see #524).

**Comment by rootfs** [comment]
I see, thank you @grantr
