### ISSUE TITLE
Proposal: Awesome Knative Eventing Sources

### ISSUE THREAD

**Issue by matzew** [knative/eventing-sources#139]
## Expected Behavior

Initial version of a **Catalog solution for Sources** that could a structured document, as discussed on the roadmap: https://docs.google.com/document/d/1z0z412rL9FsBsF8kwKxG6w7sflJLKe9hIECkc7jWfOY/edit?disco=AAAACRGJwCE

## Proposal

Instead of creating such a file here, I'd think that creating a separate "knative-awesome" repo is actually better.  This allows all Knative communities, to have some kind of "reference" for things build for, or on-top of the different knative components.

The Red Hat / CoreOS Operator framework does have such a repo:
* https://github.com/operator-framework/awesome-operators

This could be a good first step. 

/cc @vaikas-google @mattmoor @evankanderson

**Comment by mattmoor** [comment]
cc @sixolet @cppforlife 

Seems somewhat relevant to CLI (but perhaps it's still too much of an operator concern for `kn`?)

**Comment by matzew** [comment]
I think @Harwayne did check in a first doc into the docs repo.  Perhaps eventually it will be moved to a _dedicated_ repo ?

**Comment by sixolet** [comment]
Interesting. I feel like the answer to whether this is interesting to the Client group depends on whether an event source ends up being exclusively something your operator installs. If so, then looking at which ones your operator has installed and then connecting your services to them is in scope for Client, but picking event sources from the list of all event sources anyone has implemented isn't. 

However, if a developer is expected to deploy an event source like they deploy a service, then it's in scope.

**Comment by evankanderson** [comment]
I think this is a duplicate of https://github.com/knative/eventing/issues/702?

@matzew is there a particular benefit to having this in a separate repo? There's additional overhead in setting up and maintaining multiple repos, and having a separate repo will make it harder to integrate the content with the website documentation when that is set up.

**Comment by steren** [comment]
I would expect more than event sources in a `knative-awesome` repo, e.g. link to articles, clients, Knative commercial offerings. Somebody actually started one already: https://github.com/idvoretskyi/awesome-knative

Instead, for event sources, I recommend having a dedicated repo, more "official". That can be embedded into the Knative docs, and hopefully programmatically queried.

**Comment by matzew** [comment]
This is a duplicate of knative/eventing#702
