### ISSUE TITLE
Kafka adapter uses the fallback logger

### ISSUE THREAD

**Issue by grantr** [knative/eventing-sources#332]
Looked into this a bit now.  Yes, that's what the logs look like.  It appears that both prior logging messages and current ones are using the fallback logger (which is why we have the extra output).

Testing this quickly locally by commenting out the 
`logger := logging.FromContext(context.TODO())`
line and adding in
```
logger := zap.NewExample()
defer logger.Sync()
```
Seems to produce the logging format you describe.

May I suggest that, due to this being a preexisting issue, we leave it for another, more focused Issue/PR regarding the use of the fallback logger?

_Originally posted by @lberk in https://github.com/knative/eventing-sources/pull/329/files#r271099097_

**Comment by Harwayne** [comment]
My suggestion is to follow the pattern that is common in knative/eventing. 

1. Create a `zap.Logger` in `main()`.
1. Save that Logger as a field on each reconciler.
1. The very first thing that is done after a request is received by the reconciler, it stores the logger in its context:
    ```golang
    ctx := context.TODO()
    ctx = logging.WithLogger(ctx, r.logger.With(zap.Any("request", request)))
    ```
1. Everywhere else use `logging.FromContext(ctx)` to get the Logger.

knative/eventing's Trigger controller is an example.

1. Logger is created in [main()](https://github.com/knative/eventing/blob/0010da617a25bcb272cea6130ed3674c8190c015/cmd/controller/main.go#L82).
1. It is passed as an argument when creating the controller. [Passed](https://github.com/knative/eventing/blob/0010da617a25bcb272cea6130ed3674c8190c015/cmd/controller/main.go#L139), [Recieved](https://github.com/knative/eventing/blob/0010da617a25bcb272cea6130ed3674c8190c015/pkg/reconciler/v1alpha1/trigger/trigger.go#L80).
1. As soon as a reconcile request is received, the logger is [saved into the context](https://github.com/knative/eventing/blob/0010da617a25bcb272cea6130ed3674c8190c015/pkg/reconciler/v1alpha1/trigger/trigger.go#L173). All subsequent logging in the reconciler is done via `logging.FromContext`.

**Comment by Harwayne** [comment]
Actually what is likely even better, given that these all use the SDK is to only do the above steps for the SDK's `Reconciler`.

I think adding the line
```golang
ctx := context.TODO()
ctx = logging.WithLogger(ctx, r.logger.With(zap.Any("request", request)))
```
[here](https://github.com/knative/eventing-sources/blob/1ae16422a1b66b1432efc6e81bcf723106164373/pkg/controller/sdk/reconciler.go#L49) would fix the existing ones immediately.

Note that this will require saving the Logger to the Reconciler struct.

---

Possibly even better would be for the Reconciler struct to also include the name of what it is reconciling and then adding that to the logger. So the above would become:

```golang
ctx := context.TODO()
ctx = logging.WithLogger(ctx, r.logger..Named(r.name).With(zap.Any("request", request)))
```
