### ISSUE TITLE
Aggregated rules for EventTypes

### ISSUE THREAD

**Issue by nachocano** [knative/eventing-sources#389]
Would it be useful to look at using aggregated rules for EventTypes? 
@Harwayne has been thinking about this from the Channel side, but seems like we might be able to use the same concept here

**Comment by Harwayne** [comment]
Is this talking about an aggregated `ClusterRole` or `Role`? If so, what permissions need to be aggregated?

**Comment by nachocano** [comment]
`ClusterRole`... See https://github.com/knative/eventing-sources/blob/28164c8817f0ed11a86637f7c5e1d7710eb39bcc/config/201-clusterrole.yaml#L97

Came from a comment in the review of https://github.com/knative/eventing-sources/pull/300. Created this issue to track it in a potential follow up

**Comment by nachocano** [comment]
Closing for now as per @Harwayne [comment](https://github.com/knative/eventing-sources/pull/300#discussion_r280242055). May revisit later on if it makes sense to add aggregated roles.
