### ISSUE TITLE
ReceiveAdapter can't talk to Channels by default.

### ISSUE THREAD

**Issue by vaikas-google** [knative/eventing-sources#50]
## Expected Behavior
When I create a KubernetesEventSource it should be able to talk to the Channels.

## Actual Behavior
It can't due to Istio side cars.

## Steps to Reproduce the Problem

  1. Create KubernetesEventSource 
  2. it can talk to k8s event api and receive events (but see #49 )
  3. can't talk to channel

## Additional Info

**Comment by vaikas-google** [comment]
The current work around is to figure out the VirtualService representing the channel and then patching this to the Spec of it:

spec:
  gateways:
  - knative-shared-gateway.knative-serving.svc.cluster.local
  - mesh

And then find the underlying k8s service (with the same name) and replacing the spec with this:
spec:
  externalName: knative-ingressgateway.istio-system.svc.cluster.local
  sessionAffinity: None
  type: ExternalName


IMHO not a workable solution from users POV, but it's a workaround.

**Comment by n3wscott** [comment]
istio lean should be supported with https://github.com/knative/eventing/pull/524

**Comment by adamharwayne** [comment]
The GCP PubSub Source's RA is forcibly injecting the Isito sidecar for now. https://github.com/adamharwayne/knative-eventing-sources/blob/451c04a546dbcab126826c0e153a7a7f0f419fc1/pkg/controller/gcppubsub/reconcile.go#L233

**Comment by grantr** [comment]
Since #53 ContainerSource injects the Istio sidecar in all controlled containers. I think this can be closed, but feel free to reopen.
