### ISSUE TITLE
passing secret to ContainerSource

### ISSUE THREAD

**Issue by rootfs** [knative/eventing-sources#56]
I am building a new source based on container source. It is really awkward I have to plaintext secret in env. 

I am contemplating a probable solution that could work this way: 

-  adding a `SecretReference` to `ContainerSourceSpec`. 
-  by the time the deployment is created, the secret is revealed and appended into the container's env. 
-  container has to know the name of the env var and get the secret. 

That at least gives us a chance to provide and retrieve non-plaintext secret.

@n3wscott @grantr

**Comment by n3wscott** [comment]
ContainerSource is not fully featured yet. This is a feature we would like to add for sure to bring new sources to parity to what we had with feeds. Thanks for the issue to track this.

**Comment by grantr** [comment]
@rootfs if ContainerSource took a pod template spec, would that solve this problem?

**Comment by rootfs** [comment]
@grantr i believe SecretReference + PodTemplateSpec is the solution for most, if all, use cases.

**Comment by rootfs** [comment]
The app then needs to get the secret out of the secret volume, this surely works. 

A probable limitation is that the secret has to be in the same namespace as the pod. This could be a deal breaker if the container source is in e.g. eventing-system  namespace while secret is in a different namespace.

**Comment by grantr** [comment]
ContainerSource objects themselves don't go in the `eventing-system` namespace. They're created in the user's namespace along with the pod. It seems reasonable to disallow cross-namespace secret references, but do you have a counter example @rootfs?

**Comment by rootfs** [comment]
i see, that'll work, thanks!

**Comment by grantr** [comment]
Duplicate of #55
